# Generated by Django 3.2 on 2021-05-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bangladesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('Content', models.TextField()),
                ('content_image', models.ImageField(upload_to='Bangladesh_pic', verbose_name='Uplod Image')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('Content', models.TextField()),
                ('content_image', models.ImageField(upload_to='Entertainment_pic', verbose_name='Uplod Image')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='International',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('Content', models.TextField()),
                ('content_image', models.ImageField(upload_to='International_pic', verbose_name='Uplod Image')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('Content', models.TextField()),
                ('content_image', models.ImageField(upload_to='Sports_pic', verbose_name='Uplod Image')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('Content', models.TextField()),
                ('content_image', models.ImageField(upload_to='Trade_pic', verbose_name='Uplod Image')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
