# Generated by Django 3.2 on 2021-05-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_project', '0003_auto_20210519_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bangladesh',
            options={'ordering': ('-publish_time',)},
        ),
        migrations.AlterModelOptions(
            name='entertainment',
            options={'ordering': ('-publish_time',)},
        ),
        migrations.AlterModelOptions(
            name='international',
            options={'ordering': ('-publish_time',)},
        ),
        migrations.AlterModelOptions(
            name='sports',
            options={'ordering': ('-publish_time',)},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ('-publish_time',)},
        ),
    ]
